// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://lshxfzzhrynvujoatpem.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzaHhmenpocnludnVqb2F0cGVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NDcwMzUsImV4cCI6MjA2OTUyMzAzNX0.sl55XC5gmU4Yr0PPnPb3w9shb3ZZ5HTwq5ZlECFBvSw';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
